"""add feed table

Revision ID: c0d764143dc9
Revises: 8d55caf6acf4
Create Date: 2026-05-03 09:14:21.958877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d764143dc9'
down_revision: Union[str, Sequence[str], None] = '8d55caf6acf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_post_id'), 'feeds', ['post_id'], unique=False)
    op.create_index(op.f('ix_feeds_user_id'), 'feeds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_user_id'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_post_id'), table_name='feeds')
    op.drop_table('feeds')
    # ### end Alembic commands ###
